export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

export const cartConstants = {
  CART_ADD_ITEM: 'CART_ADD_ITEM',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
  CART_RESET: 'CART_RESET',
  CART_CLEAR_ITEMS: 'CART_CLEAR_ITEMS',
  SAVE_PAYMENT_METHOD: 'SAVE_PAYMENT_METHOD',
  SAVE_SHIPPING_ADDRESS: 'SAVE_SHIPPING_ADDRESS',
};

export const orderConstants = {
  FETCH_BYID_REQUEST: 'FETCH_BYID_REQUEST',
  FETCH_BYID_SUCCESS: 'FETCH_BYID_SUCCESS',
  FETCH_BYID_FAIL: 'FETCH_BYID_FAIL',

  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAIL: 'FETCH_FAIL',

  PAY_REQUEST: 'PAY_REQUEST',
  PAY_SUCCESS: 'PAY_SUCCESS',
  PAY_FAIL: 'PAY_FAIL',
  PAY_RESET: 'PAY_RESET',

  DELIVER_REQUEST: 'DELIVER_REQUEST',
  DELIVER_SUCCESS: 'DELIVER_SUCCESS',
  DELIVER_FAIL: 'DELIVER_FAIL',
  DELIVER_RESET: 'DELIVER_RESET',
};
