import Head from 'next/head';
import Link from 'next/link';
import Header from './Header';
import Footer from './Footer/Footer';
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Cart from './Cart/Cart';
const Layout = ({title, children}) => {
  return (
    <>
      <Head>
        <title>{title ? title + '' : 'Star Tech'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <ToastContainer position="bottom-center" limit={1} />
      <div className="flex min-h-screen flex-col justify-between ">
        <Header />
        <main>{children}</main>
        <Cart />
        <Footer />
      </div>
    </>
  );
};

export default Layout;
