import Head from 'next/head';
import Link from 'next/link';
import Header from './Header';
import Footer from './Footer/Footer';
const Layout = ({title, children}) => {
  return (
    <>
      <Head>
        <title>{title ? title : 'Star Tech Computer'} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <Header />
        <main>{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
