import bcrypt from 'bcryptjs';


const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Antec AX20 Mid-Tower ATX Gaming Case',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/assets/pro/1.webp',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Motorola Moto G31 Smartphone (6/128GB)',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/assets/pro/2.webp',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Samsung Galaxy F13 Smartphone (4/64GB)',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/assets/pro/3.webp',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Samsung Galaxy Z Flip4 Smartphone (8/256GB)',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/assets/pro/4.webp',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Samsung Galaxy Tab A 8.0" Snapdragon 429 2GB RAM 32GB ROM Android Tablet',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/assets/pro/5.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Epson EcoTank L3250 A4 Wi-Fi Multifunction InkTank Printer',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/assets/pro/6.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'HP Ink Tank 315 Photo and Document All-in-One Printers',
      slug: 'classic-pants1',
      category: 'Pants',
      image: '/assets/pro/7.webp',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Pantum P2506W Single Function Mono Laser Printer With Wi-Fi (22 PPM)',
      slug: 'classic-pants2',
      category: 'Pants',
      image: '/assets/pro/8.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Dell Vostro 14 3400 Core i3 11th Gen 14" HD Laptop Backlit Keyboard with 03 Years',
      slug: 'classic-pants3',
      category: 'Pants',
      image: '/assets/pro/9.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'DOEL Freedom A9 AMD A9-9425 14.1" HD Laptop',
      slug: 'classic-pants4',
      category: 'Pants',
      image: '/assets/pro/10.webp',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;
